var e = [{
  value: "0",
  text: "全国"
}, {
  value: "80",
  text: "北京",
  children: [{
    value: "88",
    text: "北京"
  }]
}, {
  value: "81",
  text: "天津",
  children: [{
    value: "89",
    text: "天津"
  }]
}, {
  value: "90",
  text: "河北",
  children: [{
    value: "124",
    text: "石家庄"
  }, {
    value: "125",
    text: "唐山"
  }, {
    value: "126",
    text: "秦皇岛"
  }, {
    value: "127",
    text: "邯郸"
  }, {
    value: "128",
    text: "邢台"
  }, {
    value: "129",
    text: "保定"
  }, {
    value: "130",
    text: "张家口"
  }, {
    value: "131",
    text: "承德"
  }, {
    value: "132",
    text: "沧州"
  }, {
    value: "133",
    text: "廊坊"
  }, {
    value: "134",
    text: "衡水"
  }]
}, {
  value: "91",
  text: "山西",
  children: [{
    value: "135",
    text: "太原"
  }, {
    value: "136",
    text: "大同"
  }, {
    value: "137",
    text: "阳泉"
  }, {
    value: "138",
    text: "长治"
  }, {
    value: "139",
    text: "晋城"
  }, {
    value: "140",
    text: "朔州"
  }, {
    value: "141",
    text: "晋中"
  }, {
    value: "142",
    text: "运城"
  }, {
    value: "143",
    text: "忻州"
  }, {
    value: "144",
    text: "临汾"
  }, {
    value: "145",
    text: "吕梁"
  }]
}, {
  value: "92",
  text: "内蒙古",
  children: [{
    value: "146",
    text: "呼和浩特"
  }, {
    value: "147",
    text: "包头"
  }, {
    value: "148",
    text: "乌海"
  }, {
    value: "149",
    text: "赤峰"
  }, {
    value: "150",
    text: "通辽"
  }, {
    value: "151",
    text: "鄂尔多斯"
  }, {
    value: "152",
    text: "呼伦贝尔"
  }, {
    value: "153",
    text: "巴彦淖尔"
  }, {
    value: "154",
    text: "乌兰察布"
  }, {
    value: "155",
    text: "兴安盟"
  }, {
    value: "156",
    text: "锡林郭勒"
  }, {
    value: "157",
    text: "阿拉善"
  }]
}, {
  value: "93",
  text: "辽宁",
  children: [{
    value: "158",
    text: "沈阳"
  }, {
    value: "159",
    text: "大连"
  }, {
    value: "160",
    text: "鞍山"
  }, {
    value: "161",
    text: "抚顺"
  }, {
    value: "162",
    text: "本溪"
  }, {
    value: "163",
    text: "丹东"
  }, {
    value: "164",
    text: "锦州"
  }, {
    value: "165",
    text: "营口"
  }, {
    value: "166",
    text: "阜新"
  }, {
    value: "167",
    text: "辽阳"
  }, {
    value: "168",
    text: "盘锦"
  }, {
    value: "169",
    text: "铁岭"
  }, {
    value: "170",
    text: "朝阳"
  }, {
    value: "171",
    text: "葫芦岛"
  }]
}, {
  value: "94",
  text: "吉林",
  children: [{
    value: "172",
    text: "长春"
  }, {
    value: "173",
    text: "吉林"
  }, {
    value: "174",
    text: "四平"
  }, {
    value: "175",
    text: "辽源"
  }, {
    value: "176",
    text: "通化"
  }, {
    value: "177",
    text: "白山"
  }, {
    value: "178",
    text: "松原"
  }, {
    value: "179",
    text: "白城"
  }, {
    value: "180",
    text: "延边"
  }]
}, {
  value: "95",
  text: "黑龙江",
  children: [{
    value: "181",
    text: "哈尔滨"
  }, {
    value: "182",
    text: "齐齐哈尔"
  }, {
    value: "183",
    text: "鸡西"
  }, {
    value: "184",
    text: "鹤岗"
  }, {
    value: "185",
    text: "双鸭山"
  }, {
    value: "186",
    text: "大庆"
  }, {
    value: "187",
    text: "伊春"
  }, {
    value: "188",
    text: "佳木斯"
  }, {
    value: "189",
    text: "七台河"
  }, {
    value: "190",
    text: "牡丹江"
  }, {
    value: "191",
    text: "黑河"
  }, {
    value: "192",
    text: "绥化"
  }, {
    value: "193",
    text: "大兴安岭"
  }]
}, {
  value: "82",
  text: "上海",
  children: [{
    value: "96",
    text: "上海"
  }]
}, {
  value: "97",
  text: "江苏",
  children: [{
    value: "195",
    text: "南京"
  }, {
    value: "196",
    text: "无锡"
  }, {
    value: "197",
    text: "徐州"
  }, {
    value: "198",
    text: "常州"
  }, {
    value: "199",
    text: "苏州"
  }, {
    value: "200",
    text: "南通"
  }, {
    value: "201",
    text: "连云港"
  }, {
    value: "202",
    text: "淮安"
  }, {
    value: "203",
    text: "盐城"
  }, {
    value: "204",
    text: "扬州"
  }, {
    value: "205",
    text: "镇江"
  }, {
    value: "206",
    text: "泰州"
  }, {
    value: "207",
    text: "宿迁"
  }]
}, {
  value: "98",
  text: "浙江",
  children: [{
    value: "208",
    text: "杭州"
  }, {
    value: "209",
    text: "宁波"
  }, {
    value: "210",
    text: "温州"
  }, {
    value: "211",
    text: "嘉兴"
  }, {
    value: "212",
    text: "湖州"
  }, {
    value: "213",
    text: "绍兴"
  }, {
    value: "214",
    text: "金华"
  }, {
    value: "215",
    text: "衢州"
  }, {
    value: "216",
    text: "舟山"
  }, {
    value: "217",
    text: "台州"
  }, {
    value: "218",
    text: "丽水"
  }]
}, {
  value: "99",
  text: "安徽",
  children: [{
    value: "219",
    text: "合肥"
  }, {
    value: "220",
    text: "芜湖"
  }, {
    value: "221",
    text: "蚌埠"
  }, {
    value: "222",
    text: "淮南"
  }, {
    value: "223",
    text: "马鞍山"
  }, {
    value: "224",
    text: "淮北"
  }, {
    value: "225",
    text: "铜陵"
  }, {
    value: "226",
    text: "安庆"
  }, {
    value: "227",
    text: "黄山"
  }, {
    value: "228",
    text: "滁州"
  }, {
    value: "229",
    text: "阜阳"
  }, {
    value: "230",
    text: "宿州"
  }, {
    value: "231",
    text: "巢湖"
  }, {
    value: "232",
    text: "六安"
  }, {
    value: "233",
    text: "亳州"
  }, {
    value: "234",
    text: "池州"
  }, {
    value: "235",
    text: "宣城"
  }]
}, {
  value: "100",
  text: "福建",
  children: [{
    value: "236",
    text: "福州"
  }, {
    value: "237",
    text: "厦门"
  }, {
    value: "238",
    text: "莆田"
  }, {
    value: "239",
    text: "三明"
  }, {
    value: "240",
    text: "泉州"
  }, {
    value: "241",
    text: "漳州"
  }, {
    value: "242",
    text: "南平"
  }, {
    value: "243",
    text: "龙岩"
  }, {
    value: "244",
    text: "宁德"
  }]
}, {
  value: "101",
  text: "江西",
  children: [{
    value: "245",
    text: "南昌"
  }, {
    value: "246",
    text: "景德镇"
  }, {
    value: "247",
    text: "萍乡"
  }, {
    value: "248",
    text: "九江"
  }, {
    value: "249",
    text: "新余"
  }, {
    value: "250",
    text: "鹰潭"
  }, {
    value: "251",
    text: "赣州"
  }, {
    value: "252",
    text: "吉安"
  }, {
    value: "253",
    text: "宜春"
  }, {
    value: "254",
    text: "抚州"
  }, {
    value: "255",
    text: "上饶"
  }]
}, {
  value: "102",
  text: "山东",
  children: [{
    value: "256",
    text: "济南"
  }, {
    value: "257",
    text: "青岛"
  }, {
    value: "258",
    text: "淄博"
  }, {
    value: "259",
    text: "枣庄"
  }, {
    value: "260",
    text: "东营"
  }, {
    value: "261",
    text: "烟台"
  }, {
    value: "262",
    text: "潍坊"
  }, {
    value: "263",
    text: "济宁"
  }, {
    value: "264",
    text: "泰安"
  }, {
    value: "265",
    text: "威海"
  }, {
    value: "266",
    text: "日照"
  }, {
    value: "267",
    text: "莱芜"
  }, {
    value: "268",
    text: "临沂"
  }, {
    value: "269",
    text: "德州"
  }, {
    value: "270",
    text: "聊城"
  }, {
    value: "271",
    text: "滨州"
  }, {
    value: "272",
    text: "荷泽"
  }]
}, {
  value: "103",
  text: "河南",
  children: [{
    value: "273",
    text: "郑州"
  }, {
    value: "274",
    text: "开封"
  }, {
    value: "275",
    text: "洛阳"
  }, {
    value: "276",
    text: "平顶山"
  }, {
    value: "277",
    text: "安阳"
  }, {
    value: "278",
    text: "鹤壁"
  }, {
    value: "279",
    text: "新乡"
  }, {
    value: "280",
    text: "焦作"
  }, {
    value: "281",
    text: "濮阳"
  }, {
    value: "282",
    text: "许昌"
  }, {
    value: "283",
    text: "漯河"
  }, {
    value: "284",
    text: "三门峡"
  }, {
    value: "285",
    text: "南阳"
  }, {
    value: "286",
    text: "商丘"
  }, {
    value: "287",
    text: "信阳"
  }, {
    value: "288",
    text: "周口"
  }, {
    value: "289",
    text: "驻马店"
  }]
}, {
  value: "104",
  text: "湖北",
  children: [{
    value: "290",
    text: "武汉"
  }, {
    value: "291",
    text: "黄石"
  }, {
    value: "292",
    text: "十堰"
  }, {
    value: "293",
    text: "宜昌"
  }, {
    value: "294",
    text: "襄樊"
  }, {
    value: "295",
    text: "鄂州"
  }, {
    value: "296",
    text: "荆门"
  }, {
    value: "297",
    text: "孝感"
  }, {
    value: "298",
    text: "荆州"
  }, {
    value: "299",
    text: "黄冈"
  }, {
    value: "300",
    text: "咸宁"
  }, {
    value: "301",
    text: "随州"
  }, {
    value: "302",
    text: "恩施"
  }]
}, {
  value: "105",
  text: "湖南",
  children: [{
    value: "304",
    text: "长沙"
  }, {
    value: "305",
    text: "株洲"
  }, {
    value: "306",
    text: "湘潭"
  }, {
    value: "307",
    text: "衡阳"
  }, {
    value: "308",
    text: "邵阳"
  }, {
    value: "309",
    text: "岳阳"
  }, {
    value: "310",
    text: "常德"
  }, {
    value: "311",
    text: "张家界"
  }, {
    value: "312",
    text: "益阳"
  }, {
    value: "313",
    text: "郴州"
  }, {
    value: "314",
    text: "永州"
  }, {
    value: "315",
    text: "怀化"
  }, {
    value: "316",
    text: "娄底"
  }, {
    value: "317",
    text: "湘西"
  }]
}, {
  value: "106",
  text: "广东",
  children: [{
    value: "318",
    text: "广州"
  }, {
    value: "319",
    text: "韶关"
  }, {
    value: "320",
    text: "深圳"
  }, {
    value: "321",
    text: "珠海"
  }, {
    value: "322",
    text: "汕头"
  }, {
    value: "323",
    text: "佛山"
  }, {
    value: "324",
    text: "江门"
  }, {
    value: "325",
    text: "湛江"
  }, {
    value: "326",
    text: "茂名"
  }, {
    value: "327",
    text: "肇庆"
  }, {
    value: "328",
    text: "惠州"
  }, {
    value: "329",
    text: "梅州"
  }, {
    value: "330",
    text: "汕尾"
  }, {
    value: "331",
    text: "河源"
  }, {
    value: "332",
    text: "阳江"
  }, {
    value: "333",
    text: "清远"
  }, {
    value: "334",
    text: "东莞"
  }, {
    value: "335",
    text: "中山"
  }, {
    value: "336",
    text: "潮州"
  }, {
    value: "337",
    text: "揭阳"
  }, {
    value: "338",
    text: "云浮"
  }]
}, {
  value: "107",
  text: "广西",
  children: [{
    value: "339",
    text: "南宁"
  }, {
    value: "340",
    text: "柳州"
  }, {
    value: "341",
    text: "桂林"
  }, {
    value: "342",
    text: "梧州"
  }, {
    value: "343",
    text: "北海"
  }, {
    value: "344",
    text: "防城港"
  }, {
    value: "345",
    text: "钦州"
  }, {
    value: "346",
    text: "贵港"
  }, {
    value: "347",
    text: "玉林"
  }, {
    value: "348",
    text: "百色"
  }, {
    value: "349",
    text: "贺州"
  }, {
    value: "350",
    text: "河池"
  }, {
    value: "351",
    text: "来宾"
  }, {
    value: "352",
    text: "崇左"
  }]
}, {
  value: "108",
  text: "海南",
  children: [{
    value: "353",
    text: "海口"
  }, {
    value: "354",
    text: "三亚"
  }]
}, {
  value: "83",
  text: "重庆",
  children: [{
    value: "109",
    text: "重庆"
  }]
}, {
  value: "110",
  text: "四川",
  children: [{
    value: "357",
    text: "成都"
  }, {
    value: "358",
    text: "自贡"
  }, {
    value: "359",
    text: "攀枝花"
  }, {
    value: "360",
    text: "泸州"
  }, {
    value: "361",
    text: "德阳"
  }, {
    value: "362",
    text: "绵阳"
  }, {
    value: "363",
    text: "广元"
  }, {
    value: "364",
    text: "遂宁"
  }, {
    value: "365",
    text: "内江"
  }, {
    value: "366",
    text: "乐山"
  }, {
    value: "367",
    text: "南充"
  }, {
    value: "368",
    text: "眉山"
  }, {
    value: "369",
    text: "宜宾"
  }, {
    value: "370",
    text: "广安"
  }, {
    value: "371",
    text: "达州"
  }, {
    value: "372",
    text: "雅安"
  }, {
    value: "373",
    text: "巴中"
  }, {
    value: "374",
    text: "资阳"
  }, {
    value: "375",
    text: "阿坝"
  }, {
    value: "376",
    text: "甘孜"
  }, {
    value: "377",
    text: "凉山"
  }]
}, {
  value: "111",
  text: "贵州",
  children: [{
    value: "378",
    text: "贵阳"
  }, {
    value: "379",
    text: "六盘水"
  }, {
    value: "380",
    text: "遵义"
  }, {
    value: "381",
    text: "安顺"
  }, {
    value: "382",
    text: "铜仁"
  }, {
    value: "383",
    text: "黔西南"
  }, {
    value: "384",
    text: "毕节地区"
  }, {
    value: "385",
    text: "黔东南"
  }, {
    value: "386",
    text: "黔南"
  }]
}, {
  value: "112",
  text: "云南",
  children: [{
    value: "387",
    text: "昆明"
  }, {
    value: "388",
    text: "曲靖"
  }, {
    value: "389",
    text: "玉溪"
  }, {
    value: "390",
    text: "保山"
  }, {
    value: "391",
    text: "昭通"
  }, {
    value: "392",
    text: "丽江"
  }, {
    value: "393",
    text: "思茅"
  }, {
    value: "394",
    text: "临沧"
  }, {
    value: "395",
    text: "楚雄"
  }, {
    value: "396",
    text: "红河"
  }, {
    value: "397",
    text: "文山"
  }, {
    value: "398",
    text: "西双版纳"
  }, {
    value: "399",
    text: "大理"
  }, {
    value: "400",
    text: "德宏"
  }, {
    value: "401",
    text: "怒江"
  }, {
    value: "402",
    text: "迪庆"
  }]
}, {
  value: "113",
  text: "西藏",
  children: [{
    value: "403",
    text: "拉萨"
  }, {
    value: "404",
    text: "昌都"
  }, {
    value: "405",
    text: "山南"
  }, {
    value: "406",
    text: "日喀则"
  }, {
    value: "407",
    text: "那曲"
  }, {
    value: "408",
    text: "阿里"
  }, {
    value: "409",
    text: "林芝"
  }]
}, {
  value: "114",
  text: "陕西",
  children: [{
    value: "410",
    text: "西安"
  }, {
    value: "411",
    text: "铜川"
  }, {
    value: "412",
    text: "宝鸡"
  }, {
    value: "413",
    text: "咸阳"
  }, {
    value: "414",
    text: "渭南"
  }, {
    value: "415",
    text: "延安"
  }, {
    value: "416",
    text: "汉中"
  }, {
    value: "417",
    text: "榆林"
  }, {
    value: "418",
    text: "安康"
  }, {
    value: "419",
    text: "商洛"
  }]
}, {
  value: "115",
  text: "甘肃",
  children: [{
    value: "420",
    text: "兰州"
  }, {
    value: "421",
    text: "嘉峪关"
  }, {
    value: "422",
    text: "金昌"
  }, {
    value: "423",
    text: "白银"
  }, {
    value: "424",
    text: "天水"
  }, {
    value: "425",
    text: "武威"
  }, {
    value: "426",
    text: "张掖"
  }, {
    value: "427",
    text: "平凉"
  }, {
    value: "428",
    text: "酒泉"
  }, {
    value: "429",
    text: "庆阳"
  }, {
    value: "430",
    text: "定西"
  }, {
    value: "431",
    text: "陇南"
  }, {
    value: "432",
    text: "临夏"
  }, {
    value: "433",
    text: "甘南"
  }]
}, {
  value: "116",
  text: "青海",
  children: [{
    value: "434",
    text: "西宁"
  }, {
    value: "435",
    text: "海东"
  }, {
    value: "436",
    text: "海北"
  }, {
    value: "437",
    text: "黄南"
  }, {
    value: "438",
    text: "海南"
  }, {
    value: "439",
    text: "果洛"
  }, {
    value: "440",
    text: "玉树"
  }, {
    value: "441",
    text: "海西"
  }]
}, {
  value: "117",
  text: "宁夏",
  children: [{
    value: "442",
    text: "银川"
  }, {
    value: "443",
    text: "石嘴山"
  }, {
    value: "444",
    text: "吴忠"
  }, {
    value: "445",
    text: "固原"
  }, {
    value: "446",
    text: "中卫"
  }]
}, {
  value: "118",
  text: "新疆",
  children: [{
    value: "447",
    text: "乌鲁木齐"
  }, {
    value: "448",
    text: "克拉玛依"
  }, {
    value: "449",
    text: "吐鲁番"
  }, {
    value: "450",
    text: "哈密"
  }, {
    value: "451",
    text: "昌吉"
  }, {
    value: "452",
    text: "博尔塔拉"
  }, {
    value: "453",
    text: "巴音郭楞"
  }, {
    value: "454",
    text: "阿克苏"
  }, {
    value: "455",
    text: "克孜勒苏"
  }, {
    value: "456",
    text: "喀什"
  }, {
    value: "457",
    text: "和田"
  }, {
    value: "458",
    text: "伊犁"
  }, {
    value: "459",
    text: "塔城"
  }, {
    value: "460",
    text: "阿勒泰"
  }]
}, {
  value: "119",
  text: "台湾"
}, {
  value: "120",
  text: "香港"
}, {
  value: "121",
  text: "澳门"
}];

module.exports = e;